{
	"version": 1595942687,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/buttonplay-sheet0.png",
		"images/soundic-sheet0.png",
		"images/soundic-sheet1.png",
		"images/enemies-sheet0.png",
		"images/enemies-sheet1.png",
		"images/enemies2-sheet0.png",
		"images/enemies2-sheet1.png",
		"images/enemies3-sheet0.png",
		"images/powerup-sheet0.png",
		"images/powerupprogress-sheet0.png",
		"images/powerupprogress-sheet1.png",
		"images/heart-sheet0.png",
		"images/healthbg-sheet0.png",
		"images/map-sheet0.png",
		"images/spawntrigger-sheet0.png",
		"images/spawnpoint1-sheet0.png",
		"images/shootpoint-sheet0.png",
		"images/shootpointhandler-sheet0.png",
		"images/pause-sheet0.png",
		"images/damageline-sheet0.png",
		"images/close-sheet0.png",
		"images/buttonhome-sheet0.png",
		"images/blueparticles.png",
		"images/gamebg-sheet0.png",
		"images/gamebg2-sheet0.png",
		"images/greenparticles.png",
		"images/redparticles.png",
		"images/powerupparticle.png",
		"images/yellowparticles.png",
		"images/loadingbg-sheet0.png",
		"media/gun shoot.m4a",
		"media/gun shoot.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/war music.m4a",
		"media/war music.ogg",
		"media/can.m4a",
		"media/can.ogg",
		"media/touch.m4a",
		"media/touch.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}